indaba-backend:
  image: "amidatech/greyscale-backend:${INDABA_ENV}"
  environment:
    RDS_USERNAME: ${RDS_USERNAME}
    RDS_PASSWORD: ${RDS_PASSWORD}
    RDS_HOSTNAME: ${RDS_HOSTNAME}
    RDS_TESTUSER: ${RDS_TESTUSER}
    INDABA_PG_DB: ${INDABA_PG_DB}
  ports:
  - "3005:3005"
  links:
  - "memcached"

memcached:
  image: "memcached:latest"
  expose:
  - "11211"

indaba-frontend:
  image: "amidatech/greyscale-client:${INDABA_ENV}"
  links:
  - "indaba-backend"
  environment:
    INDABA_URL: http://indaba-backend:3005
  ports:
  - "80:80"
