apiVersion: v1
kind: Service
metadata:
  labels:
    app: indaba-nginx
  name: indaba-nginx
  namespace: default
spec:
  ports:
  - name: nginx-port-http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: nginx-port-https
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: indaba-nginx
  type: LoadBalancer
