# Can be repurposed for other deployments and services by modifying names and image deifinitions
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: indaba-sandbox-5-greyscale
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: indaba-sandbox-5-greyscale
    spec:
      containers:
      - name: indaba-sandbox-5-greyscale
        image: amidatech/indaba-backend:dev
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: indaba-sandbox-5-configmap
        ports:
        - name: nodejs-port
          containerPort: 3005
