#!/bin/sh
set -e

POSTGRES_PREFIX_CMD="psql --username ${POSTGRES_USER}"

echo "Creating database role: ${GREYSCALE_PG_USER}"

$POSTGRES_PREFIX_CMD <<-EOSQL
CREATE USER "${GREYSCALE_PG_USER}" WITH CREATEDB PASSWORD '${GREYSCALE_PG_PASSWORD}';
EOSQL
