#!/bin/sh
set -e

POSTGRES_PREFIX_CMD="psql --username ${POSTGRES_USER}"

echo "Creating database: ${AUTH_SERVICE_PG_DB}"

$POSTGRES_PREFIX_CMD <<EOSQL
CREATE DATABASE "${AUTH_SERVICE_PG_DB}" OWNER "${POSTGRES_USER}";
EOSQL

echo "Creating database: ${SURVEY_SERVICE_PG_DB}"

$POSTGRES_PREFIX_CMD <<EOSQL
CREATE DATABASE "${SURVEY_SERVICE_PG_DB}" OWNER "${POSTGRES_USER}";
EOSQL

echo "Creating database: ${MESSAGING_SERVICE_PG_DB}"

$POSTGRES_PREFIX_CMD <<EOSQL
CREATE DATABASE "${MESSAGING_SERVICE_PG_DB}" OWNER "${POSTGRES_USER}";
EOSQL

echo "Creating database: ${GREYSCALE_PG_DB}"

$POSTGRES_PREFIX_CMD <<EOSQL
CREATE DATABASE "${GREYSCALE_PG_DB}" OWNER "${GREYSCALE_PG_USER}";
EOSQL
