version: '3.5'
services:
  # amida-messaging-microservice:
  #   image: amidatech/messaging-service:dev
  #   depends_on:
  #     - indaba-db
  #   container_name: amida-messaging-microservice
  #   volumes:
  #   - /app/
  #   ports:
  #   - ${MESSAGE_SERVICE_PORT:-4001}:${MESSAGE_SERVICE_PORT:-4001}
  #   env_file:
  #   - .env
  #   environment:
  #   - DEBUG=amida-messaging-microservice:*
  #
  # amida-survey-microservice:
  #   image: amidatech/survey-service:dev
  #   depends_on:
  #     - indaba-db
  #   container_name: amida-survey-microservice
  #   volumes:
  #   - /app/
  #   ports:
  #   - ${SURVEY_SERVICE_PORT:-9005}:${SURVEY_SERVICE_PORT:-9005}
  #   env_file:
  #   - .env
  #   environment:
  #   - DEBUG=amida-survey-microservice:*
  #
  amida-auth-microservice:
    image: amidatech/auth-service:dev
    depends_on:
      - indaba-db
    container_name: amida-auth-microservice
    command:
      - yarn migrate && yarn serve
    volumes:
    - /app/
    ports:
    - ${AUTH_SERVICE_PORT:-4000}:${AUTH_SERVICE_PORT:-4000}
    env_file:
    - .env
    environment:
    - DEBUG=amida-auth-microservice:*

  indaba-db:
    image: postgres:9.6
    volumes:
      - ./10-create_users.sh:/docker-entrypoint-initdb.d/10-create_users.sh
      - ./20-create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
    environment:
    - POSTGRES_USER=${POSTGRES_USER:-amida}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-amida}
    - GREYSCALE_PG_USER=${GREYSCALE_PG_USER:-indaba}
    - GREYSCALE_PG_PASSWORD=${GREYSCALE_PG_PASSWORD:-abadnI1!}
    - AUTH_SERVICE_PG_DB=${AUTH_SERVICE_PG_DB:-amida-auth-microservice}
    - SURVEY_SERVICE_PG_DB=${SURVEY_SERVICE_PG_DB:-amida-survey-microservice}
    - MESSAGING_SERVICE_PG_DB=${AUTH_SERVICE_PG_DB:-amida-messaging-microservice}
    - GREYSCALE_PG_DB=${GREYSCALE_PG_DB:-indaba}


networks:
  default:
    external:
      name: ${DOCKER_NETWORK:-indaba-network}
